apiVersion: v1
kind: Namespace
metadata:
    name: development
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: ping-pong-02a73fb
    name: ping-pong-deployment-02a73fb
    namespace: development
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ping-pong-02a73fb
    template:
        metadata:
            labels:
                app: ping-pong-02a73fb
        spec:
            containers:
              - image: manedurphy/ping-pong:development
                livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 3
                    periodSeconds: 3
                name: ping-pong-02a73fb
                ports:
                  - containerPort: 8080
                startupProbe:
                    failureThreshold: 30
                    httpGet:
                        path: /healthz
                        port: 8080
                    periodSeconds: 10
