apiVersion: v1
kind: Namespace
metadata:
    name: pr-aa28c4c
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: ping-pong-aa28c4c
    name: ping-pong-deployment-aa28c4c
    namespace: pr-aa28c4c
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ping-pong-aa28c4c
    template:
        metadata:
            labels:
                app: ping-pong-aa28c4c
        spec:
            containers:
              - image: manedurphy/ping-pong:aa28c4c
                livenessProbe:
                    httpGet:
                        path: /healthz
                        port: 8080
                    initialDelaySeconds: 3
                    periodSeconds: 3
                name: ping-pong-aa28c4c
                ports:
                  - containerPort: 8080
                startupProbe:
                    failureThreshold: 30
                    httpGet:
                        path: /healthz
                        port: 8080
                    periodSeconds: 10
