name: Release

on:
  push:
    branches: [ master ]

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Build and deploy new release
      run: |
        docker buildx create --name my-builder --use
        make docker-push
