name: Testing

on:
  pull_request:
    branches: [ development ]

jobs:

  unit_testing:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Unit Tests
      run: go test -v ./test

    - name: Generate PR Yaml
      run: make pr

    - name: Commit changes
      run: |
        git config --global user.email "github-actions-bot@github.com"
        git config --global user.name "github-actions"
        git add . && git commit -m "Generated PR testing environment configuration"
        git push
