name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:

  testing:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Unit Tests
      run: go test -v ./test

    - name: Generate PR Yaml
      run: make pr

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Build image for test environment
      run: |
        docker buildx create --name my-builder --use
        make docker-push-pr

    - name: Commit changes
      run: |
        git config --global user.email "github-actions-bot@github.com"
        git config --global user.name "github-actions"
        git add . && git commit -m "Generated PR testing environment configuration"
        git push
