name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
      run: |
        echo hello > file.txt

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Unit Tests
      run: go test -v ./test
