name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create text file
      run: echo hello > file.txt

    - name: Commit changes
      run: |
        git config --global user.email "dummy@email.com"
        git config --global user.name "First Last"
        git add . && git commit -a -m "Added text file"
        git push

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5

    - name: Unit Tests
      run: go test -v ./test
